//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calico.persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducto
    {
        public int prod_proc_id { get; set; }
        public string prod_compania { get; set; }
        public string prod_codigo { get; set; }
        public string prod_codigoBarras { get; set; }
        public string prod_descripcion { get; set; }
        public string prod_descripcionFantasia { get; set; }
        public string prod_clase { get; set; }
        public string prod_unidadMedida { get; set; }
        public decimal prod_cantidadPorUnidadVenta { get; set; }
        public decimal prod_cantidadPorCaja { get; set; }
        public decimal prod_cantidadPorPallet { get; set; }
        public decimal prod_pesoUnidad { get; set; }
        public decimal prod_pesoCaja { get; set; }
        public decimal prod_pesoPallet { get; set; }
        public decimal prod_altoUnidad { get; set; }
        public decimal prod_altoCaja { get; set; }
        public decimal prod_altoPallet { get; set; }
        public decimal prod_anchoUnidad { get; set; }
        public decimal prod_anchoCaja { get; set; }
        public decimal prod_anchoPallet { get; set; }
        public decimal prod_largoUnidad { get; set; }
        public decimal prod_largoCaja { get; set; }
        public decimal prod_largoPallet { get; set; }
        public string prod_categoriaUbicacion { get; set; }
        public string prod_categoriaPicking { get; set; }
        public string prod_categoriaReposicion { get; set; }
        public string prod_categoriaEmbalaje { get; set; }
        public string prod_rubro { get; set; }
        public string prod_subRubro { get; set; }
        public string prod_referenciaA { get; set; }
        public string prod_referenciaB { get; set; }
        public bool prod_manejaLote { get; set; }
        public bool prod_manejaSerie { get; set; }
        public decimal prod_precioCosto { get; set; }
        public decimal prod_precioVenta { get; set; }
        public decimal prod_diasVencimiento { get; set; }
        public bool prod_esProductoPadre { get; set; }
    
        public virtual tblProceso tblProceso { get; set; }
    }
}
